# Generated by Django 6.0.3 on 2026-03-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='Приглашён организатором'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_event', 'Новое мероприятие'), ('new_comment', 'Новый комментарий'), ('new_review', 'Новый отзыв'), ('registration_confirmed', 'Запись подтверждена'), ('registration_cancelled', 'Запись отменена'), ('event_cancelled', 'Мероприятие отменено'), ('invitation', 'Приглашение на мероприятие')], max_length=30, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('attended', 'Посетил')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
