# Generated by Django 6.0.3 on 2026-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_moderation_comment_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_event', 'Новое мероприятие'), ('new_comment', 'Новый комментарий'), ('new_review', 'Новый отзыв'), ('registration_confirmed', 'Запись подтверждена'), ('registration_cancelled', 'Запись отменена'), ('event_cancelled', 'Мероприятие отменено'), ('invitation', 'Приглашение на мероприятие'), ('event_pending', 'Заявка на мероприятие'), ('event_approved', 'Мероприятие одобрено'), ('event_rejected', 'Мероприятие отклонено')], max_length=30, verbose_name='Тип'),
        ),
    ]
