# Generated by Django 6.0.3 on 2026-04-16 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название площадки'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_url',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт площадки'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_event', 'Новое мероприятие'), ('new_comment', 'Новый комментарий'), ('new_review', 'Новый отзыв'), ('registration_confirmed', 'Запись подтверждена'), ('registration_cancelled', 'Запись отменена'), ('event_cancelled', 'Мероприятие отменено'), ('invitation', 'Приглашение на мероприятие'), ('event_pending', 'Заявка на мероприятие'), ('event_approved', 'Мероприятие одобрено'), ('event_rejected', 'Мероприятие отклонено'), ('new_event_from_organizer', 'Новое мероприятие от организатора')], max_length=30, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='OrganizerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписка на организатора',
                'verbose_name_plural': 'Подписки на организаторов',
                'unique_together': {('user', 'organizer')},
            },
        ),
    ]
