# Generated by Django 6.0.3 on 2026-03-28 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('specialist', 'Специалист'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('competencies', models.TextField(blank=True, verbose_name='Компетенции')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('moderation_status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Одобрен')], default='draft', max_length=20, verbose_name='Статус модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль специалиста',
                'verbose_name_plural': 'Профили специалистов',
                'ordering': ['full_name'],
            },
        ),
    ]
