# Generated by Django 6.0.3 on 2026-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_specialistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, help_text='Опишите ваш опыт работы на мероприятиях', verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='user',
            name='looking_for_work',
            field=models.BooleanField(default=False, help_text='Отметьте, если вы открыты для предложений', verbose_name='Ищу работу'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Ссылка на видео/сайт с примерами работ', verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='Например: "Ведение мероприятий, работа с аудиторией, MS Office"', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Роль'),
        ),
        migrations.DeleteModel(
            name='SpecialistProfile',
        ),
    ]
