# Generated by Django 6.0.3 on 2026-03-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_experience_user_looking_for_work_user_portfolio_and_more'),
        ('events', '0008_registration_is_invited_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='events.category', verbose_name='Специализация'),
        ),
    ]
